// <auto-generated />
using System;
using AniVault.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AniVault.Migrations
{
    [DbContext(typeof(AniVaultDbContext))]
    partial class AniVaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AniVault.Database.AnimeEpisodesSetting", b =>
                {
                    b.Property<int>("MALAnimeId")
                        .HasColumnType("integer")
                        .HasColumnName("mal_anime_id");

                    b.Property<string>("AnimeFolderPath")
                        .HasColumnType("text")
                        .HasColumnName("anime_folder_path");

                    b.Property<short?>("CourEpisodeNumberGap")
                        .HasColumnType("smallint")
                        .HasColumnName("cour_episode_number_gap");

                    b.Property<bool>("DownloadLastEpisode")
                        .HasColumnType("boolean")
                        .HasColumnName("download_last_episode");

                    b.Property<string>("FileNameTemplate")
                        .HasColumnType("text")
                        .HasColumnName("file_name_template");

                    b.Property<int>("TelegramChannelId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_channel_id");

                    b.Property<bool>("UseGapForEpNum")
                        .HasColumnType("boolean")
                        .HasColumnName("use_gap_for_ep_num");

                    b.HasKey("MALAnimeId")
                        .HasName("pk_anime_episodes_setting");

                    b.HasIndex("TelegramChannelId")
                        .IsUnique()
                        .HasDatabaseName("ix_anime_episodes_setting_telegram_channel_id");

                    b.ToTable("AnimeEpisodesSetting");
                });

            modelBuilder.Entity("AniVault.Database.ApiUser", b =>
                {
                    b.Property<int>("ApiUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("api_user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApiUserId"));

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("api_key");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_name");

                    b.HasKey("ApiUserId")
                        .HasName("pk_api_user");

                    b.HasIndex("ApiKey")
                        .IsUnique()
                        .HasDatabaseName("ix_api_user_api_key");

                    b.ToTable("ApiUser");
                });

            modelBuilder.Entity("AniVault.Database.ScheduledTask", b =>
                {
                    b.Property<int>("ScheduledTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("scheduled_task_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScheduledTaskId"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int?>("IntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("interval_seconds");

                    b.Property<DateTime>("LastFinish")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_finish");

                    b.Property<DateTime>("LastStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_start");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("task_name");

                    b.HasKey("ScheduledTaskId")
                        .HasName("pk_scheduled_task");

                    b.ToTable("ScheduledTask");
                });

            modelBuilder.Entity("AniVault.Database.SystemConfigurationParameter", b =>
                {
                    b.Property<int>("ConfigurationParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("configuration_parameter_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConfigurationParameterId"));

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parameter_name");

                    b.Property<int>("ParameterType")
                        .HasColumnType("integer")
                        .HasColumnName("parameter_type");

                    b.Property<string>("ParameterValue")
                        .HasColumnType("text")
                        .HasColumnName("parameter_value");

                    b.HasKey("ConfigurationParameterId")
                        .HasName("pk_system_configuration_parameters");

                    b.HasIndex("ParameterName")
                        .IsUnique()
                        .HasDatabaseName("ix_system_configuration_parameters_parameter_name");

                    b.ToTable("system_configuration_parameters", (string)null);
                });

            modelBuilder.Entity("AniVault.Database.TelegramChannel", b =>
                {
                    b.Property<int>("TelegramChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("telegram_channel_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TelegramChannelId"));

                    b.Property<long>("AccessHash")
                        .HasColumnType("bigint")
                        .HasColumnName("access_hash");

                    b.Property<bool>("AutoDownloadEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_download_enabled");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel_name");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("TelegramChannelId")
                        .HasName("pk_telegram_channel");

                    b.HasIndex("ChatId")
                        .IsUnique()
                        .HasDatabaseName("ix_telegram_channel_chat_id");

                    b.ToTable("TelegramChannel");
                });

            modelBuilder.Entity("AniVault.Database.TelegramMediaDocument", b =>
                {
                    b.Property<int>("TelegramMediaDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("telegram_media_document_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TelegramMediaDocumentId"));

                    b.Property<long>("AccessHash")
                        .HasColumnType("bigint")
                        .HasColumnName("access_hash");

                    b.Property<long>("DataTransmitted")
                        .HasColumnType("bigint")
                        .HasColumnName("data_transmitted");

                    b.Property<int>("DownloadStatus")
                        .HasColumnType("integer")
                        .HasColumnName("download_status");

                    b.Property<int?>("ErrorType")
                        .HasColumnType("integer")
                        .HasColumnName("error_type");

                    b.Property<long>("FileId")
                        .HasColumnType("bigint")
                        .HasColumnName("file_id");

                    b.Property<byte[]>("FileReference")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("file_reference");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("filename");

                    b.Property<string>("FilenameFromTelegram")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("filename_from_telegram");

                    b.Property<string>("FilenameToUpdate")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("filename_to_update");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mime_type");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<int>("TelegramMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_message_id");

                    b.HasKey("TelegramMediaDocumentId")
                        .HasName("pk_telegram_media_document");

                    b.HasIndex("FileId")
                        .IsUnique()
                        .HasDatabaseName("ix_telegram_media_document_file_id");

                    b.HasIndex("TelegramMessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_telegram_media_document_telegram_message_id");

                    b.ToTable("TelegramMediaDocument");
                });

            modelBuilder.Entity("AniVault.Database.TelegramMessage", b =>
                {
                    b.Property<int>("TelegramMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("telegram_message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TelegramMessageId"));

                    b.Property<int>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    b.Property<int>("MessageStatus")
                        .HasColumnType("integer")
                        .HasColumnName("message_status");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message_text");

                    b.Property<DateTime>("ReceivedDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_datetime");

                    b.Property<int>("TelegramChannelId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_channel_id");

                    b.Property<DateTime?>("UpdateDatetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_datetime");

                    b.HasKey("TelegramMessageId")
                        .HasName("pk_telegram_message");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_telegram_message_message_id");

                    b.HasIndex("TelegramChannelId")
                        .HasDatabaseName("ix_telegram_message_telegram_channel_id");

                    b.ToTable("TelegramMessage");
                });

            modelBuilder.Entity("AniVault.Database.AnimeEpisodesSetting", b =>
                {
                    b.HasOne("AniVault.Database.TelegramChannel", "TelegramChannel")
                        .WithOne("AnimeEpisodesSetting")
                        .HasForeignKey("AniVault.Database.AnimeEpisodesSetting", "TelegramChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_anime_episodes_setting_telegram_channel_telegram_channel_id");

                    b.Navigation("TelegramChannel");
                });

            modelBuilder.Entity("AniVault.Database.TelegramMediaDocument", b =>
                {
                    b.HasOne("AniVault.Database.TelegramMessage", "TelegramMessage")
                        .WithOne("MediaDocument")
                        .HasForeignKey("AniVault.Database.TelegramMediaDocument", "TelegramMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telegram_media_document_telegram_message_telegram_message_id");

                    b.Navigation("TelegramMessage");
                });

            modelBuilder.Entity("AniVault.Database.TelegramMessage", b =>
                {
                    b.HasOne("AniVault.Database.TelegramChannel", "TelegramChannel")
                        .WithMany("TelegramMessages")
                        .HasForeignKey("TelegramChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telegram_message_telegram_channel_telegram_channel_id");

                    b.Navigation("TelegramChannel");
                });

            modelBuilder.Entity("AniVault.Database.TelegramChannel", b =>
                {
                    b.Navigation("AnimeEpisodesSetting");

                    b.Navigation("TelegramMessages");
                });

            modelBuilder.Entity("AniVault.Database.TelegramMessage", b =>
                {
                    b.Navigation("MediaDocument");
                });
#pragma warning restore 612, 618
        }
    }
}
